import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  sidebar: {
    'Getting Started': [
      'getting-started/introduction',
      'getting-started/installation',
      'getting-started/basic-example',
    ],
    'Basics': [
      'basics/metadata',
      'basics/columns',
      'basics/documents-and-sub-documents',
      'basics/mixins',
    ],
    Advanced: [
      'advanced/indexes',
      'advanced/hooks',
      'advanced/discriminators',
      'advanced/query-methods',
      'advanced/local-column',
      'advanced/plugins',
      'advanced/async-model-compilation',
    ],
    Utilities: [
      'utilities/utilities',
    ]
  }
};

export default sidebars;
