name: Nx Distributed Tasks [PR]

on:
  pull_request:
    branches:
      - main

env:
  BUILD_ARTIFACTS: dist-artifacts
  DEPENDENCIES_CACHE: cache-node-modules
  NX_CACHE: cache-nx
  SERVICEBUS_CONNECTION_STRING: ${{ secrets.SERVICEBUS_CONNECTION_STRING }}

jobs:

  vars:
    runs-on: ubuntu-latest
    outputs:
      GITHUB_HEAD_REF: ${{ github.event.pull_request.head.sha }}
      GITHUB_BASE_REF: ${{ steps.GITHUB_BASE_REF.outputs.value }}
    steps:
      - id: GITHUB_HEAD_REF
        run: echo "::set-output name=value::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"
      - id: GITHUB_BASE_REF
        run: echo "::set-output name=value::$(echo ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}})"

  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('yarn.lock') }}
      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --pure-lockfile
      - name: Build local nx plugins
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          yarn nx build nx-build-pipe
          yarn nx build nx-api-extractor
      - name: Cache dist (for nx-build-pipe, etc...)
        id: cache-build
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}

  # format:
  #   runs-on: ubuntu-latest
  #   needs: [vars, install-deps]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Cache node modules
  #       uses: actions/cache@v2
  #       with:
  #         path: node_modules
  #         key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('yarn.lock') }}
  #     - run: git fetch --no-tags --prune origin ${{ needs.vars.outputs.GITHUB_BASE_REF }} ${{ needs.vars.outputs.GITHUB_HEAD_REF }}
  #     - name: Compute Nx arguments
  #       if: needs.vars.outputs.GITHUB_HEAD_REF != needs.vars.outputs.GITHUB_BASE_REF
  #       run: echo "NX_ARGUMENTS=--base=origin/${{ needs.vars.outputs.GITHUB_BASE_REF }}" >> $GITHUB_ENV
  #     - run: node --max-old-space-size=8000 ./node_modules/@nrwl/cli/bin/nx.js format:check $NX_ARGUMENTS
  #     # - run: git fetch --no-tags --prune --depth=5 origin main
  #     # - run: echo "GITHUB_BASE_SHA=$([[ "$GITHUB_REF" == "refs/origin/main" ]] && echo "origin/main~1" || echo "origin/main")" >> $GITHUB_ENV
  #     # - run: node --max-old-space-size=8000 ./node_modules/@nrwl/cli/bin/nx.js format:check --base=$GITHUB_BASE_SHA

  distributed-task:
    runs-on: ubuntu-latest
    needs: [vars, install-deps]
    strategy:
      fail-fast: false
      matrix:
        target: ['test', 'build']
        index: [1, 2, 3, 4]
    env:
      count: 4
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - run: |
          echo "git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules origin ${GITHUB_SHA}:${GITHUB_REF}"
          git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules origin ${GITHUB_SHA}:${GITHUB_REF}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('yarn.lock') }}
      - name: Cache dist (for nx-build-pipe, etc...)
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
      - name: Cache Nx
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: ${{ env.NX_CACHE }}-${{ hashFiles('yarn.lock') }}-${{ matrix.target }}-${{ matrix.index }}-${{ github.sha }}
          restore-keys: |
            ${{ env.NX_CACHE }}-${{ hashFiles('yarn.lock') }}-${{ matrix.target }}-${{ matrix.index }}-
            ${{ env.NX_CACHE }}-${{ hashFiles('yarn.lock') }}-
            ${{ env.NX_CACHE }}-
      - name: Compute Nx arguments
        if: matrix.target == 'build'
        run: echo "NX_ARGUMENTS=--prod --with-deps" >> "$GITHUB_ENV"
      - name: Compute Nx arguments
        if: matrix.target == 'test'
        run: echo 'NX_ARGUMENTS=--codeCoverage --coverageReporters=lcov' >> "$GITHUB_ENV"
      - name: nx run-many:${{ matrix.target }}
        run: |
          echo "node ./tools/build/run-many.js ${{ matrix.target }} ${{ matrix.index }} ${{ env.count }} ${GITHUB_REF#refs/remotes/} main $NX_ARGUMENTS"
          node ./tools/build/run-many.js ${{ matrix.target }} ${{ matrix.index }} ${{ env.count }} ${GITHUB_REF#refs/remotes/} main $NX_ARGUMENTS
      - name: Merge Coverage Reports
        if: matrix.target == 'test'
        run: node ./tools/build/coverageMerger.js
      - name: Upload coverage to Coveralls
        if: matrix.target == 'test'
        continue-on-error: true
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
