name: GH Pages on release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Define branch name'
        required: true
        default: 'main'
  release:
    types: [created]

env:
  BUILD_ARTIFACTS: dist-artifacts
  DEPENDENCIES_CACHE: cache-node-modules
  NX_CACHE: cache-nx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt install libsdl-pango-dev
          yarn install --pure-lockfile
      - run: npx nx run-many --target gh-pages --parallel 1
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          branch: gh-pages
          folder: dist/gh-pages
